### PR TITLE
Don't skip bash shell extension on Windows

### PR DESCRIPTION
**Pull request by rotu**

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Please share some context what use cases you have tried using this functionality on Windows.

Please update the classifiers of the package (https://github.com/colcon/colcon-bash/blob/cc1ae805dd921e7b40ead4dc69ff9a118c562c02/setup.cfg#L17-L18) to include Windows as well as address the test failure.

**Comment by rotu** [comment]
Context: I'm trying to run colcon in bash on WSL:

```
sudo apt install -y python3-pip cmake
cd /mnt/c/opt/ros/master
export PATH=`python3 -c "import sysconfig, os; print(sysconfig.get_path('scripts', os.name + '_user'))"`:$PATH
python3 -m pip install --upgrade pip setuptools wheel
python3 -m pip install --upgrade colcon-common-extensions
# python3 -m pip install --upgrade git+https://github.com/rotu/colcon-bash.git@patch-1 git+https://github.com/rotu/colcon-core.git@patch-4
colcon build --packages-up-to ros_environment
```

Though it seems there may be more than one problem at play here:
```
Starting >>> ros_environment
[32.764s] ERROR:colcon.colcon_core.shell:Exception in shell extension 'sh': Expected ['.', '/mnt/c/opt/ros/master/build/ros_environment/colcon_command_prefix_build.sh', '&&', 'env'] to pass: /bin/sh: 3: /mnt/c/opt/ros/master/install/ament_c: not foundhare/ament_cmake_core/environment/ament_prefix_path.sh:
: not found /mnt/c/opt/ros/master/install/ament_cmake_core/share/ament_cmake_core/environment/path.sh:
/bin/sh: 6: /mnt/c/opt/ros/master/install/ament_cmake_core/share/ament_cmake_core/environment/path.sh: Syntax error: end of file unexpected (expecting "then")

Traceback (most recent call last):
  File "/home/dan/.local/lib/python3.8/site-packages/colcon_core/shell/__init__.py", line 288, in get_command_environment
    return await extension.generate_command_environment(
  File "/home/dan/.local/lib/python3.8/site-packages/colcon_core/shell/sh.py", line 126, in generate_command_environment    env = await get_environment_variables(cmd, cwd=str(build_base))
  File "/home/dan/.local/lib/python3.8/site-packages/colcon_core/shell/__init__.py", line 325, in get_environment_variables
    output = await check_output(cmd, cwd=cwd, shell=shell)
  File "/home/dan/.local/lib/python3.8/site-packages/colcon_core/subprocess.py", line 109, in check_output
    assert not rc, \
AssertionError: Expected ['.', '/mnt/c/opt/ros/master/build/ros_environment/colcon_command_prefix_build.sh', '&&', 'env'] to pass: /bin/sh: 3: /mnt/c/opt/ros/master/install/ament_cmake_core/share/ament_cmake_core/environment/ament_prefix_pa: not found
: not found /mnt/c/opt/ros/master/install/ament_cmake_core/share/ament_cmake_core/environment/path.sh:
/bin/sh: 6: /mnt/c/opt/ros/master/install/ament_cmake_core/share/ament_cmake_core/environment/path.sh: Syntax error: end of file unexpected (expecting "then")


[32.765s] ERROR:colcon.colcon_cmake.task.cmake.build:Could not find a shell extension for the command environment
Failed   <<< ros_environment [0.32s, exited with code 1]

Summary: 2 packages finished [32.4s]
  1 package failed: ros_environment
```

**Comment by dirk-thomas** [comment]
> I'm trying to run colcon in bash on WSL:

Instead of blankly enabling this for Windows then I would rather like it to be only enabled on WSL if that is possible to distinguish.

**Comment by rotu** [comment]
> > I'm trying to run colcon in bash on WSL:
> 
> Instead of blankly enabling this for Windows then I would rather like it to be only enabled on WSL if that is possible to distinguish.

I think I'm missing some assumptions here. What purpose does skipping the extension serve? Under what circumstance would colcon work if we skip colcon-bash but NOT if we enable it?

**Comment by dirk-thomas** [comment]
> What purpose does skipping the extension serve?

To not generate additional files (which will confuse users) on platforms where they can't be used anyway. (And avoid the overhead of generating the files.)

**Comment by dirk-thomas** [comment]
@rotu Are you still planning to iterate on this PR?

**Comment by dirk-thomas** [comment]
@rotu Friendly ping.

**Comment by dirk-thomas** [comment]
Closing due to no response.

**Pull request closed without merging**
